# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#     file: en_us.py
#     date: 2018-05-05
#   author: paul.dautry
#  purpose:
#
#  license:
#    hid_decoder Decoder for USB HID data
#    Copyright (C) 2018 paul.dautry
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# =============================================================================
#  IMPORTS
# =============================================================================
from keys import Key
# =============================================================================
#  GLOBALS / CONFIG
# =============================================================================
KEYMAP = {
    Key.NONE:                   ('', ''),
    Key.ERROR_ROLL_OVER:        ('', ''),
    Key.POST_FAIL:              ('', ''),
    Key.ERROR_UNDEFINED:        ('', ''),
    Key.KEY_A:                  ('a', 'A'),
    Key.KEY_B:                  ('b', 'B'),
    Key.KEY_C:                  ('c', 'C'),
    Key.KEY_D:                  ('d', 'D'),
    Key.KEY_E:                  ('e', 'E'),
    Key.KEY_F:                  ('f', 'F'),
    Key.KEY_G:                  ('g', 'G'),
    Key.KEY_H:                  ('h', 'H'),
    Key.KEY_I:                  ('i', 'I'),
    Key.KEY_J:                  ('j', 'J'),
    Key.KEY_K:                  ('k', 'K'),
    Key.KEY_L:                  ('l', 'L'),
    Key.KEY_M:                  ('m', 'M'),
    Key.KEY_N:                  ('n', 'N'),
    Key.KEY_O:                  ('o', 'O'),
    Key.KEY_P:                  ('p', 'P'),
    Key.KEY_Q:                  ('q', 'Q'),
    Key.KEY_R:                  ('r', 'R'),
    Key.KEY_S:                  ('s', 'S'),
    Key.KEY_T:                  ('t', 'T'),
    Key.KEY_U:                  ('u', 'U'),
    Key.KEY_V:                  ('v', 'V'),
    Key.KEY_W:                  ('w', 'W'),
    Key.KEY_X:                  ('x', 'X'),
    Key.KEY_Y:                  ('y', 'Y'),
    Key.KEY_Z:                  ('z', 'Z'),
    Key.KEY_1:                  ('1', '!'),
    Key.KEY_2:                  ('2', '@'),
    Key.KEY_3:                  ('3', '#'),
    Key.KEY_4:                  ('4', '$'),
    Key.KEY_5:                  ('5', '%'),
    Key.KEY_6:                  ('6', '^'),
    Key.KEY_7:                  ('7', '&'),
    Key.KEY_8:                  ('8', '*'),
    Key.KEY_9:                  ('9', '('),
    Key.KEY_0:                  ('0', ')'),
    Key.KEY_ENTER:              ('[ENTER]', '[ENTER]'),
    Key.KEY_ESCAPE:             ('[ESCAPE]', '[ESCAPE]'),
    Key.KEY_DELETE:             ('[DELETE]', '[DELETE]'),
    Key.KEY_TAB:                ('[TAB]', '[TAB]'),
    Key.KEY_SPACE:              (' ', ' '),
    Key.KEY_MINUS:              ('-', '_'),
    Key.KEY_EQUAL:              ('=', '+'),
    Key.KEY_LEFT_BRACKET:       ('[', '{'),
    Key.KEY_RIGHT_BRACKET:      (']', '}'),
    Key.KEY_BACKSLASH:          ('\\', '|'),
    Key.KEY_HASH:               ('#', '~'),
    Key.KEY_SEMICOLON:          (';', ':'),
    Key.KEY_QUOTE:              ("'", '"'),
    Key.KEY_GRAVE_ACCENT:       ('`', '~'),
    Key.KEY_COMMA:              (',', '<'),
    Key.KEY_DOT:                ('.', '>'),
    Key.KEY_SLASH:              ('/', '?'),
    Key.KEY_CAPS_LOCK:          ('[CAPS_LOCK]', '[CAPS_LOCK]'),
    Key.KEY_F1:                 ('[F1]', '[F1]'),
    Key.KEY_F2:                 ('[F2]', '[F2]'),
    Key.KEY_F3:                 ('[F3]', '[F3]'),
    Key.KEY_F4:                 ('[F4]', '[F4]'),
    Key.KEY_F5:                 ('[F5]', '[F5]'),
    Key.KEY_F6:                 ('[F6]', '[F6]'),
    Key.KEY_F7:                 ('[F7]', '[F7]'),
    Key.KEY_F8:                 ('[F8]', '[F8]'),
    Key.KEY_F9:                 ('[F9]', '[F9]'),
    Key.KEY_F10:                ('[F10]', '[F10]'),
    Key.KEY_F11:                ('[F11]', '[F11]'),
    Key.KEY_F12:                ('[F12]', '[F12]'),
    Key.KEY_PRINT_SCREEN:       ('[PRINT_SCREEN]', '[PRINT_SCREEN]'),
    Key.KEY_SCROLL_LOCK:        ('[SCROLL_LOCK]', '[SCROLL_LOCK]'),
    Key.KEY_PAUSE:              ('[PAUSE]', '[PAUSE]'),
    Key.KEY_INSERT:             ('[INSERT]', '[INSERT]'),
    Key.KEY_HOME:               ('[HOME]', '[HOME]'),
    Key.KEY_PAGE_UP:            ('[PAGE_UP]', '[PAGE_UP]'),
    Key.KEY_DELETE_FWD:         ('[DELETE_FWD]', '[DELETE_FWD]'),
    Key.KEY_END:                ('[END]', '[END]'),
    Key.KEY_PAGE_DOWN:          ('[PAGE_DOWN]', '[PAGE_DOWN]'),
    Key.KEY_RIGHT_ARROW:        ('[RIGHT_ARROW]', '[RIGHT_ARROW]'),
    Key.KEY_LEFT_ARROW:         ('[LEFT_ARROW]', '[LEFT_ARROW]'),
    Key.KEY_DOWN_ARROW:         ('[DOWN_ARROW]', '[DOWN_ARROW]'),
    Key.KEY_UP_ARROW:           ('[UP_ARROW]', '[UP_ARROW]'),
    Key.KEY_NUM_LOCK:           ('[NUM_LOCK]', '[NUM_LOCK]'),
    Key.KEY_PAD_SLASH:          ('/', '/'),
    Key.KEY_PAD_STAR:           ('*', '*'),
    Key.KEY_PAD_MINUS:          ('-', '-'),
    Key.KEY_PAD_PLUS:           ('+', '+'),
    Key.KEY_PAD_RETURN:         ('[ENTER]', '[ENTER]'),
    Key.KEY_PAD_1:              ('[END]', '1'),
    Key.KEY_PAD_2:              ('[DOWN_ARROW]', '2'),
    Key.KEY_PAD_3:              ('[PAGE_DOWN]', '3'),
    Key.KEY_PAD_4:              ('[LEFT_ARROW]', '4'),
    Key.KEY_PAD_5:              ('', '5'),
    Key.KEY_PAD_6:              ('[RIGHT_ARROW]', '6'),
    Key.KEY_PAD_7:              ('[HOME]', '7'),
    Key.KEY_PAD_8:              ('[UP_ARROW]', '8'),
    Key.KEY_PAD_9:              ('PAGE_UP', '9'),
    Key.KEY_PAD_0:              ('[INSERT]', '0'),
    Key.KEY_PAD_DOT:            ('[DELETE_FWD]', '.'),
    Key.KEY_NON_US_BACKSLASH: ('', ''),
    Key.KEY_APPLICATION: ('', ''),
    Key.KEY_POWER: ('', ''),
    Key.KEY_PAD_EQUAL: ('', ''),
    Key.KEY_F13: ('', ''),
    Key.KEY_F14: ('', ''),
    Key.KEY_F15: ('', ''),
    Key.KEY_F16: ('', ''),
    Key.KEY_F17: ('', ''),
    Key.KEY_F18: ('', ''),
    Key.KEY_F19: ('', ''),
    Key.KEY_F20: ('', ''),
    Key.KEY_F21: ('', ''),
    Key.KEY_F22: ('', ''),
    Key.KEY_F23: ('', ''),
    Key.KEY_F24: ('', ''),
    Key.KEY_EXECUTE: ('', ''),
    Key.KEY_HELP: ('', ''),
    Key.KEY_MENU: ('', ''),
    Key.KEY_SELECT: ('', ''),
    Key.KEY_STOP: ('', ''),
    Key.KEY_AGAIN: ('', ''),
    Key.KEY_UNDO: ('', ''),
    Key.KEY_CUT: ('', ''),
    Key.KEY_COPY: ('', ''),
    Key.KEY_PASTE: ('', ''),
    Key.KEY_FIND: ('', ''),
    Key.KEY_MUTE: ('', ''),
    Key.KEY_VOLUME_UP: ('', ''),
    Key.KEY_VOLUME_DOWN: ('', ''),
    Key.KEY_LOCKING_CAPS_LOCK: ('', ''),
    Key.KEY_LOCKING_NUM_LOCK: ('', ''),
    Key.KEY_LOCKING_SCROLL_LOCK: ('', ''),
    Key.KEY_PAD_COMMA: ('', ''),
    Key.KEY_PAD_EQUAL_SIGN: ('', ''),
    Key.KEY_INTERNATIONAL1: ('', ''),
    Key.KEY_INTERNATIONAL2: ('', ''),
    Key.KEY_INTERNATIONAL3: ('', ''),
    Key.KEY_INTERNATIONAL4: ('', ''),
    Key.KEY_INTERNATIONAL5: ('', ''),
    Key.KEY_INTERNATIONAL6: ('', ''),
    Key.KEY_INTERNATIONAL7: ('', ''),
    Key.KEY_INTERNATIONAL8: ('', ''),
    Key.KEY_INTERNATIONAL9: ('', ''),
    Key.KEY_LANG1: ('', ''),
    Key.KEY_LANG2: ('', ''),
    Key.KEY_LANG3: ('', ''),
    Key.KEY_LANG4: ('', ''),
    Key.KEY_LANG5: ('', ''),
    Key.KEY_LANG6: ('', ''),
    Key.KEY_LANG7: ('', ''),
    Key.KEY_LANG8: ('', ''),
    Key.KEY_LANG9: ('', ''),
    Key.KEY_ALT_ERASE: ('', ''),
    Key.KEY_SYSREQ_ATTENTION: ('', ''),
    Key.KEY_CANCEL: ('', ''),
    Key.KEY_CLEAR: ('', ''),
    Key.KEY_PRIOR: ('', ''),
    Key.KEY_RETURN: ('', ''),
    Key.KEY_SEPARATOR: ('', ''),
    Key.KEY_OUT: ('', ''),
    Key.KEY_OPER: ('', ''),
    Key.KEY_CLEAR_AGAIN: ('', ''),
    Key.KEY_CRSEL_PROPS: ('', ''),
    Key.KEY_EXSEL: ('', ''),
    Key.KEY_PAD_00: ('', ''),
    Key.KEY_PAD_000: ('', ''),
    Key.THOUSANDS_SEP: ('', ''),
    Key.DECIMAL_SEP: ('', ''),
    Key.CURRENCY_UNIT: ('', ''),
    Key.CURRENCY_SUB_UNIT: ('', ''),
    Key.KEY_PAD_LEFT_PARENTHESIS: ('', ''),
    Key.KEY_PAD_RIGHT_PARENTHESIS: ('', ''),
    Key.KEY_PAD_LEFT_BRACE: ('', ''),
    Key.KEY_PAD_RIGHT_BRACE: ('', ''),
    Key.KEY_PAD_TAB: ('', ''),
    Key.KEY_PAD_BACKSPACE: ('[DELETE]', '[DELETE]'),
    Key.KEY_PAD_A: ('', ''),
    Key.KEY_PAD_B: ('', ''),
    Key.KEY_PAD_C: ('', ''),
    Key.KEY_PAD_D: ('', ''),
    Key.KEY_PAD_E: ('', ''),
    Key.KEY_PAD_F: ('', ''),
    Key.KEY_PAD_XOR: ('', ''),
    Key.KEY_PAD_CIRCUMFLEX_ACCENT: ('', ''),
    Key.KEY_PAD_PERCENT: ('', ''),
    Key.KEY_PAD_LT: ('', ''),
    Key.KEY_PAD_GT: ('', ''),
    Key.KEY_PAD_AND: ('', ''),
    Key.KEY_PAD_LOGICAL_AND: ('', ''),
    Key.KEY_PAD_PIPE: ('', ''),
    Key.KEY_PAD_LOGICAL_OR: ('', ''),
    Key.KEY_PAD_COLON: ('', ''),
    Key.KEY_PAD_HASH: ('', ''),
    Key.KEY_PAD_SPACE: ('', ''),
    Key.KEY_PAD_AT: ('', ''),
    Key.KEY_PAD_EXCLAMATION: ('', ''),
    Key.KEY_PAD_MEMORY_STORE: ('', ''),
    Key.KEY_PAD_MEMORY_RECALL: ('', ''),
    Key.KEY_PAD_MEMORY_CLEAR: ('', ''),
    Key.KEY_PAD_MEMORY_ADD: ('', ''),
    Key.KEY_PAD_MEMORY_SUBTRACT: ('', ''),
    Key.KEY_PAD_MEMORY_MULTIPLY: ('', ''),
    Key.KEY_PAD_MEMORY_DIVIDE: ('', ''),
    Key.KEY_PAD_PLUS_MINUS: ('', ''),
    Key.KEY_PAD_CLEAR: ('', ''),
    Key.KEY_PAD_CLEAR_ENTRY: ('', ''),
    Key.KEY_PAD_BINARY: ('', ''),
    Key.KEY_PAD_OCTAL: ('', ''),
    Key.KEY_PAD_DECIMAL: ('', ''),
    Key.KEY_PAD_HEXADECIMAL: ('', ''),
    Key.KEY_LEFT_CTRL: ('', ''),
    Key.KEY_LEFT_SHIFT: ('', ''),
    Key.KEY_LEFT_ALT: ('', ''),
    Key.KEY_LEFT_GUI: ('', ''),
    Key.KEY_RIGHT_CTRL: ('', ''),
    Key.KEY_RIGHT_SHIFT: ('', ''),
    Key.KEY_RIGHT_ALT: ('', ''),
    Key.KEY_RIGHT_GUI: ('', ''),
}